package Attedence;


import Input.AttendenceInput;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Uday
 */
public class AttandanceDetails extends javax.swing.JFrame {

    public AttandanceDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        regestrationno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        subjectname = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        intakecode = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        lecturerdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        timein = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        timeout = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        attendence = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 80));
        jLabel1.setText("Student Attandance Sheet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        back.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(21, 88, 68));
        back.setText(" Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 90, -1));

        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(21, 88, 68));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 90, -1));

        save.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(21, 88, 68));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, -1));

        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(21, 88, 68));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 90, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 88, 68));
        jLabel5.setText("Registration No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 90, 110, -1));

        regestrationno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(regestrationno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 87, 136, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 88, 68));
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 128, -1, -1));

        firstname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 125, 136, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 88, 68));
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 166, -1, -1));

        lastname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 163, 136, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 88, 68));
        jLabel9.setText("Subject Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        subjectname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subjectname.setForeground(new java.awt.Color(21, 88, 68));
        subjectname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SNA", "SDM", "SAAD", "MWT" }));
        getContentPane().add(subjectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 136, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 88, 68));
        jLabel10.setText("intake code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        intakecode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        intakecode.setForeground(new java.awt.Color(21, 88, 68));
        intakecode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NP1F1609IT", "NP1F1609BM", "" }));
        getContentPane().add(intakecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 136, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(21, 88, 68));
        jLabel11.setText("Lecturer date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        lecturerdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(lecturerdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 136, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(21, 88, 68));
        jLabel12.setText("Time in");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 65, -1));

        timein.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(timein, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 136, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 88, 68));
        jLabel13.setText("Time Out");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        timeout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(timeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 136, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 88, 68));
        jLabel14.setText("Attendence");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 20));

        attendence.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        attendence.setForeground(new java.awt.Color(21, 88, 68));
        attendence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "/ Present", "/ Absent", "/Late", "/ Athorize Absent" }));
        getContentPane().add(attendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 136, -1));

        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(21, 88, 68));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 90, -1));

        view.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(21, 88, 68));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Student s=new Student();
        s.setVisible(true);
       
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Loginwel l=new Loginwel();
        l.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        if(!(Pattern.matches("^[0-9]+",regestrationno.getText()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",firstname.getText())) 
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",lastname.getText()))
                   && !(Pattern.matches("^[0-9]+-",lecturerdate.getText())) 
                   && !(Pattern.matches("^[0-9]+^[a-zA-Z:\\s]*$",timein.getText())) 
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",subjectname.getSelectedItem().toString()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",attendence.getSelectedItem().toString()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",intakecode.getSelectedItem().toString()))
                   && !(Pattern.matches("^[0-9]+^[a-zA-Z:\\s]*$",timeout.getText()))
                   )
           {
             JOptionPane.showMessageDialog(null,"Invalid Input");  
           } else{
        AttendenceInput ai=new AttendenceInput();
        ai.Add(regestrationno.getText(),firstname.getText(),lastname.getText(),subjectname.getSelectedItem().toString(),
             intakecode.getSelectedItem().toString(),lecturerdate.getText(),timein.getText(), timeout.getText(), 
            attendence.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null,"Student Attendence Save Successfully");
        regestrationno.setText("");
        firstname.setText("");
        lastname.setText("");
        lecturerdate.setText("");
        timein.setText("");
        timeout.setText("");
        
        } 
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
            if(!(Pattern.matches("^[0-9]+",regestrationno.getText()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",firstname.getText())) 
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",lastname.getText()))
                   && !(Pattern.matches("^[0-9]+-",lecturerdate.getText())) 
                   && !(Pattern.matches("^[0-9]+^[a-zA-Z:\\s]*$",timein.getText())) 
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",subjectname.getSelectedItem().toString()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",attendence.getSelectedItem().toString()))
                   && !(Pattern.matches("^[a-zA-Z\\s]*$",intakecode.getSelectedItem().toString()))
                   && !(Pattern.matches("^[0-9]+^[a-zA-Z:\\s]*$",timeout.getText())))
           {
             JOptionPane.showMessageDialog(null,"Invalid Input");  
           } else{
        AttendenceInput ai=new AttendenceInput();
        ai.update(regestrationno.getText(),firstname.getText(),lastname.getText(),subjectname.getSelectedItem().toString(),
             intakecode.getSelectedItem().toString(),lecturerdate.getText(),timein.getText(), timeout.getText(), 
            attendence.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null,"Student Attendence Update Successfully");}
            regestrationno.setText("");
        firstname.setText("");
        lastname.setText("");
        lecturerdate.setText("");
        timein.setText("");
        timeout.setText("");
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViewAttendence va=new ViewAttendence();
        va.setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttandanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttandanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttandanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttandanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttandanceDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> attendence;
    private javax.swing.JButton back;
    private javax.swing.JButton exit;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> intakecode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField lecturerdate;
    private javax.swing.JButton logout;
    private javax.swing.JTextField regestrationno;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> subjectname;
    private javax.swing.JTextField timein;
    private javax.swing.JTextField timeout;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
